// "use client"

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navigation from "./components/navigation";
import { ClerkProvider } from "@clerk/nextjs";
// import { useState } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: {
    default: "Next.js Tutorials - Codevolution",
    template: "%s | Codevolution"
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const [input,setInput] = useState("")
  return (
    <ClerkProvider>
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="bg-slate-900 text-white p-4 text-center">
            {/* <p>Welcome to Next.js 15 Crash Course</p> */}
            <Navigation />
          </header>
          {/* <input value={input} onChange={e => setInput(e.target.value) } /> */}
        {children}
        <footer className="bg-slate-900 text-white p-4 text-center">
            Codevolution
          </footer>
      </body>
    </html>
    </ClerkProvider>
  );
}
